Update readme
natura-cosmeticos/SonarEsLintPlugin pull request #1
Opened 2018-10-22 19:05 UTC by darthaud

2018-10-22 19:55 UTC, handrus requested changes
@darthaud please fix wrong link and upgrade the first part of the file according to the comment

2018-10-22 19:55 UTC, handrus commented on README.md
Link to download the plugin on line #6 is wrong (forked repo.
Also we should update the readme explaining why we forked it, what are we doing different and if we have intention to make PRs to the original plugin.

2018-10-23 21:31 UTC, handrus reviewed
[![LGTM](http://www.lgtm.in/p/ker1)](http://www.lgtm.in/i/ker1)

[:+1:](http://www.lgtm.in/u/ker1) [:-1:](http://www.lgtm.in/r/ker1)

2018-10-23 21:31 UTC, handrus approved these changes

2019-03-08 21:18 UTC, FabricioFFC approved these changes

2019-03-08 21:18 UTC, merged

2019-09-19 12:35 UTC, sleroy commented
Good work guys. I have never seen the notifications about your work before. I have done the merge and I preparing a new version inlcuding your modifications.

Thanks a lot !

2020-01-09 19:06 UTC, handrus commented
Hi @sleroy it seems to me that all we have here is already integrated at your repo. Thanks a lot!